### ISSUE TITLE
Scheme should be 'https', but is 'http'.

### ISSUE THREAD

**Issue by hexagon6** [manomayam/manas#34]
I try to use manas as storage pod.

For this I set up manas with tls-certificates in my local network.

When using `https://myhost/resource` as reference for a solid document from my solid application I get a http 400 error in the browser console / fetching from web client.

Client log looks like this:

```
Error: Fetching the Resource at [https://myhost/resource] failed: [400] [] {"type":"https://httpstatuses.com/400","status":400,"title":"Bad Request","detail":"Invalid request target"}.
```

Server log looks like this:

```stdout
  2023-11-06T09:50:07.195644Z DEBUG manas_http::service::impl_::reconstruct_target_uri: Target uri builder: Builder { scheme: Some("http"), authority: None, path: "/", query: None, fragment: None, normalize: false }
    at crates/manas_http/src/service/impl_/reconstruct_target_uri.rs:140

  2023-11-06T09:50:07.195917Z ERROR manas_http::service::impl_::reconstruct_target_uri: Error in reconstructing target uri.
    at crates/manas_http/src/service/impl_/reconstruct_target_uri.rs:155
```

Tracing back the error it looks to me the scheme variable is initialized with 'http' and only updated when Forward-headers are present. In my setup this is not the case (no reverse-proxy setting those I assume).

So maybe something is either wrong in the logic of https://github.com/manomayam/manas/blob/9eb1fb2003af8bcdc673b2dc5b6672a63f63e10a/crates/manas_http/src/service/impl_/reconstruct_target_uri.rs#L86 or I need to change something on my setup so the default scheme is initialized as 'https'.

**Comment by hexagon6** [comment]
My config.toml looks like this:

```toml
[storage.space]
# Uri of the storage root.
root_uri = "https://myhost/"
```

**Comment by damooo** [comment]
You  have to specify tls configuraion in config.toml, and  also should bind to correct port. Can you post full `config.toml` with dummy secrets?
```toml
[server.tls]
# Cert pem file path.
cert_path = "/path/to/cert.pem"

# Key pem file path.
key_path = "/path/to/key.pem"
```
