### ISSUE TITLE
port of the server doesn't bind to the machine's port.

### ISSUE THREAD

**Issue by argahsuknesib** [manomayam/manas#57]
Hello,
I am unsure if it a machine issue but I installed Community Solid Server on the same machine with the port 3000 and it is accessible from outside of the machine as well.
I am wondering if there could be something wrong in my config.

```toml
dev_mode = true
[storage.space]
root_uri = "http://n061-14a.wall2.ilabt.iminds.be:3001/"
owner_id = "https://argahsuknesib.github.io/me/"
[storage.repo]
databrowser_enabled = true
[storage.repo.backend]
root = "/users/kbisenug/data-manas/"
[server]
addr = "127.0.0.1:3001"
```

I tried fixing and putting the addr of the server to be the port of the machine i.e 

```toml
addr = "http://n061-14a.wall2.ilabt.iminds.be:3001/" 
```
but I get an error 
```bash
r: invalid socket address syntax
    at crates/manas_server/src/recipe/mod.rs:90

Error: invalid socket address syntax
```

What do you think could be wrong in this case? Thanks for the help already.
